name: disprot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cudatoolkit=12.1
  - tqdm=4.66.1
  - numpy=1.25.0
  - setuptools=68.2.2
  - wheel=0.41.2
  - vs2019_runtime
  - vc=14.3
  - ipython
  - pip:
    - omegaconf==2.3.0
    - scikit-learn==1.3.2
    - matplotlib==3.7.3
    - seaborn==0.13.0
    - pandas==2.2.0
    - pytorch-lightning==2.2.0
    - transformers==4.42.0
    - swanlab==0.5.4
    - biopython==1.83
    - colorama==0.4.6
    - python-dotenv==1.0.0
    - tensorboard==2.15.1
    - pyyaml==6.0.1 