# 总氨基酸类型数量（20种标准氨基酸+1种不确定类型'X'）
residue_types:
    21

# 无序蛋白质预测模型配置

# 模型配置
model:
    d_model: 64       # 模型隐藏维度（减小以加快测试）
    n_head: 4         # 注意力头数
    n_layer: 2        # Transformer编码器层数（减少以加快测试）
    i_dim: 21         # 输入维度（氨基酸编码）
    o_dim: 2          # 输出维度（二分类：有序/无序）

# 数据配置
data:
    data_path: "mock_data.pkl"
    max_seq_len: null  # 最大序列长度，null表示不限制
    train_rate: 0.7    # 训练集比例
    valid_rate: 0.2    # 验证集比例

# 训练配置
train:
    epochs: 3         # 训练轮数（减少以加快测试）
    save_interval: 1  # 保存模型的间隔（每多少个epoch保存一次）
    eval_interval: 1  # 评估的间隔（每多少个epoch验证一次）
    gpu: 0            # 使用的GPU编号，-1表示使用CPU
    early_stop_patience: 10  # 早停耐心值，连续多少个评估间隔没有提升就停止训练
    checkpoint_dir: "checkpoints"  # 检查点保存目录
    use_swanlab: false  # 是否使用SwanLab进行实验跟踪
    
    # 数据加载器配置
    dataloader:
        batch_size: 4   # 批处理大小（减小以加快测试）
        shuffle: true   # 是否打乱数据
        num_workers: 2  # 数据加载的线程数（减少以减少资源使用）
        drop_last: false # 是否丢弃最后不完整的批次
    
    # 优化器配置
    optimizer:
        lr: 5.0e-4      # 学习率（增加以加快收敛）
        weight_decay: 1.0e-4  # 权重衰减

# 预测配置
predict:
    output_dir: "predictions"  # 预测结果输出目录
    visualize: true  # 是否可视化预测结果